import type { Metadata } from 'next'
import { Space_Grotesk, Roboto } from 'next/font/google'
import './globals.css'
import { ChildProps } from '@/types/indeex'
import { cn, localization } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { languages } from '@/i18n/settings'
import { dir } from 'i18next'
import { ClerkProvider } from '@clerk/nextjs'
import CookiesProviderWrapper from '@/components/providers/cookie-provider'
import { Toaster } from '@/components/ui/sonner'

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
})

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '300', '400', '500', '700', '900'],
})

export async function generateStaticParams() {
  return languages.map(lng => ({ lng }))
}

export const metadata: Metadata = {
  title: 'MBS Academy',
  description: 'Generated by create next app',
}

interface Props extends ChildProps {
  params: {
    lng: string
  }
}
async function RootLayout({ children, params }: Props) {
  const { lng } = await params
  const local = localization(lng)
  return (
    <html
      lang={lng}
      dir={dir(lng)}
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        'overflow-x-hidden',
        roboto.variable,
        spaceGrotesk.variable,
      )}
    >
      <body className='min-h-full flex flex-col'>
        <ClerkProvider localization={local}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <CookiesProviderWrapper>
              {children} <Toaster position='top-center' />
            </CookiesProviderWrapper>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}

export default RootLayout
